name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.24.0-alpine
    steps:
      - uses: actions/checkout@v1
      - run: ./scripts/check/check.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2-beta
        with:
          go-version: 1.15
      - run: make ci-test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          file: ./.test_coverage.txt

  publish-webhook:
    if: startsWith(github.ref, 'refs/tags/')
    env:
      TAG_IMAGE_LATEST: "true"
      WEBHOOK_IMAGE_NAME: docker.pkg.github.com/${GITHUB_REPOSITORY}/webhook
    needs: [check, test]
    name: Publish webhook
    runs-on: ubuntu-latest
    # Only run in master and when has a tag.
    steps:
      - name: Set tag on VERSION env var
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/checkout@v1
      - name: Build image
        run: make build-webhook-image
      - name: Docker login
        run: docker login ${DOCKER_HOST} -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
        env:
          DOCKER_HOST: docker.pkg.github.com
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${GITHUB_ACTOR}
      - name: Publish image
        run: make publish-webhook-image
        
  publish-envtemplate:
    if: startsWith(github.ref, 'refs/tags/')
    env:
      TAG_IMAGE_LATEST: "true"
      ENVTEMPLATE_IMAGE_NAME: docker.pkg.github.com/${GITHUB_REPOSITORY}/envtemplate
    needs: [check, test]
    name: Publish envtemplate
    runs-on: ubuntu-latest
    # Only run in master and when has a tag.
    steps:
      - name: Set tag on VERSION env var
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/checkout@v1
      - name: Build image
        run: make build-envtemplate-image
      - name: Docker login
        run: docker login ${DOCKER_HOST} -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
        env:
          DOCKER_HOST: docker.pkg.github.com
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${GITHUB_ACTOR}
      - name: Publish image
        run: make publish-envtemplate-image
      
